import React from 'react';
import { Activity, ArrowRight, Box, Cloud, Cpu, Globe2, Plus, Server, Zap } from 'lucide-react';
import { useApp } from '../context/AppContext';

export const Deployments: React.FC = () => {
  const { deployments, models, setView, setSelectedDeploymentId, startDeployment } = useApp();
  const onlineCount = deployments.filter((item) => item.status === 'online').length;

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 md:px-6 animate-fade-in">
      <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-display text-[10px] font-black uppercase tracking-[0.2em] text-cyan-400">Infrastructure workspace</p><h1 className="mt-2 font-display text-3xl font-black text-white">Deployments</h1><p className="mt-1 font-sans text-xs text-slate-400">Manage your mock ModelVerse endpoints from one place.</p></div><button onClick={() => setView('library')} className="flex items-center gap-2 self-start rounded-xl bg-white/5 px-4 py-2.5 font-display text-xs font-bold text-slate-200 transition hover:bg-white/10"><Box size={14} /> Browse Library</button></div>
      <div className="mb-8 grid gap-3 sm:grid-cols-3"><Stat label="Total deployments" value={String(deployments.length)} icon={Server} /><Stat label="Online" value={String(onlineCount)} icon={Activity} tone="text-emerald-400" /><Stat label="Mock usage" value="₹103.20" icon={Zap} tone="text-cyan-400" /></div>
      {deployments.length === 0 ? <EmptyState models={models} startDeployment={startDeployment} /> : <div className="grid gap-5 lg:grid-cols-2">{deployments.map((deployment) => { const model = models.find((item) => item.id === deployment.modelId); return <button key={deployment.id} onClick={() => { setSelectedDeploymentId(deployment.id); setView('deployment-detail'); }} className="group rounded-2xl glass-panel p-5 text-left transition hover:border-cyan-500/30"><div className="flex items-start justify-between gap-4"><div><p className="font-display text-[10px] font-black uppercase tracking-wider text-cyan-400">{model?.category || 'Model'}</p><h2 className="mt-1 font-display text-lg font-black text-white group-hover:text-cyan-400">{model?.name || deployment.modelId}</h2><p className="mt-0.5 font-mono text-xs text-slate-500">{deployment.name}</p></div><Status status={deployment.status} /></div><div className="mt-5 grid grid-cols-2 gap-3 border-y border-white/5 py-4 sm:grid-cols-4"><Metric label="Region" value={deployment.region.replace('India - ', '')} icon={Globe2} /><Metric label="Compute" value={deployment.compute.type.replace(' GPU', '')} icon={Cpu} /><Metric label="Requests" value={deployment.metrics.requests.toLocaleString()} icon={Activity} /><Metric label="Usage" value={`₹${deployment.metrics.estimatedCost.toFixed(2)}`} icon={Zap} /></div><div className="mt-4 flex items-center justify-between"><span className="font-sans text-[10px] text-slate-500">{deployment.environment} · {deployment.scaling.mode === 'auto' ? 'Auto Scale' : 'Fixed'}</span><span className="flex items-center gap-1 font-display text-[10px] font-bold uppercase text-cyan-400">Manage <ArrowRight size={12} /></span></div></button>})}</div>}
    </div>
  );
};

const EmptyState: React.FC<{ models: any[]; startDeployment: (id: string) => void }> = ({ models, startDeployment }) => <div className="rounded-3xl border border-dashed border-white/10 p-12 text-center"><Cloud size={34} className="mx-auto text-cyan-400/60" /><h2 className="mt-4 font-display text-lg font-black text-white">No deployments yet</h2><p className="mx-auto mt-1 max-w-sm font-sans text-xs leading-relaxed text-slate-500">Own a model, then deploy it to create your first mock API endpoint.</p><button onClick={() => startDeployment(models.find((model) => model.owned || model.installed)?.id || models[0].id)} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2.5 font-display text-xs font-black uppercase text-slate-950"><Plus size={14} /> Deploy an owned model</button></div>;
const Stat: React.FC<{ label: string; value: string; icon: React.ElementType; tone?: string }> = ({ label, value, icon: Icon, tone = 'text-slate-200' }) => <div className="rounded-2xl glass-panel p-4"><Icon size={16} className="text-slate-500" /><strong className={`mt-3 block font-display text-2xl font-black ${tone}`}>{value}</strong><span className="font-sans text-[10px] text-slate-500">{label}</span></div>;
const Metric: React.FC<{ label: string; value: string; icon: React.ElementType }> = ({ label, value, icon: Icon }) => <div><Icon size={13} className="mb-1 text-slate-600" /><span className="block truncate font-display text-xs font-bold text-slate-200">{value}</span><span className="font-sans text-[9px] text-slate-500">{label}</span></div>;
const Status: React.FC<{ status: string }> = ({ status }) => <span className={`flex items-center gap-1.5 font-display text-[10px] font-black uppercase ${status === 'online' ? 'text-emerald-400' : status === 'deploying' ? 'text-amber-400' : 'text-slate-500'}`}><span className="h-2 w-2 rounded-full bg-current" />{status}</span>;
