import React, { useState } from 'react';
import { ArrowLeft, BarChart3, Clipboard, Copy, FileText, KeyRound, Pause, RefreshCw, Settings2, Terminal, Trash2 } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { ModelTags } from './ModelTags';

const codeExamples = {
  JavaScript: `const response = await fetch(\n  "https://api.modelverse.dev/v1/pixelforge-production",\n  {\n    method: "POST",\n    headers: {\n      "Authorization": "Bearer YOUR_MODELVERSE_API_KEY",\n      "Content-Type": "application/json"\n    },\n    body: JSON.stringify({ prompt: "A futuristic city at sunset" })\n  }\n);\n\nconst result = await response.json();`,
  Python: `import requests\n\nresponse = requests.post(\n  "https://api.modelverse.dev/v1/pixelforge-production",\n  headers={"Authorization": "Bearer YOUR_MODELVERSE_API_KEY"},\n  json={"prompt": "A futuristic city at sunset"}\n)\nresult = response.json()`,
  cURL: `curl -X POST \\\n  https://api.modelverse.dev/v1/pixelforge-production \\\n  -H "Authorization: Bearer YOUR_MODELVERSE_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{"prompt":"A futuristic city at sunset"}'`
};

export const DeploymentDetail: React.FC = () => {
  const { deployments, models, selectedDeploymentId, setView, regenerateApiKey, deleteDeployment, addToast } = useApp();
  const deployment = deployments.find((item) => item.id === selectedDeploymentId) || deployments[0];
  const model = models.find((item) => item.id === deployment?.modelId);
  const [tab, setTab] = useState<'overview' | 'api' | 'usage' | 'logs' | 'settings'>('overview');
  const [codeTab, setCodeTab] = useState<keyof typeof codeExamples>('JavaScript');
  const [revealed, setRevealed] = useState(false);

  if (!deployment || !model) return <div className="p-10 text-center text-slate-500">Deployment not found.</div>;
  const endpoint = `https://api.modelverse.dev/v1/${deployment.name}`;
  const apiKey = revealed ? deployment.api.apiKey : 'mv_test_••••••••••••••••';
  const copy = async (value: string, message: string) => { await navigator.clipboard?.writeText(value); addToast(message, 'success'); };

  return <div className="mx-auto max-w-7xl px-4 py-8 md:px-6 animate-fade-in"><button onClick={() => setView('deployments')} className="mb-6 flex items-center gap-2 font-sans text-xs text-slate-500 hover:text-white"><ArrowLeft size={14} /> All deployments</button><div className="flex flex-col justify-between gap-5 border-b border-white/5 pb-7 md:flex-row md:items-end"><div><div className="flex items-center gap-3"><span className="font-display text-[10px] font-black uppercase tracking-wider text-cyan-400">{model.category}</span><Status /></div><h1 className="mt-2 font-display text-3xl font-black text-white">{model.name}</h1><p className="mt-1 font-mono text-sm text-slate-400">{deployment.name}</p><ModelTags tags={model.tags} limit={3} className="mt-3" /></div><div className="flex flex-wrap gap-2"><button onClick={() => addToast('Deployment is already running in prototype mode.', 'info')} className="flex items-center gap-2 rounded-xl bg-emerald-500/10 px-4 py-2.5 font-display text-xs font-bold text-emerald-400"><Pause size={14} /> Stop</button><button onClick={() => addToast('Mock deployment restart queued.', 'info')} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 font-display text-xs font-bold text-slate-200"><RefreshCw size={14} /> Restart</button></div></div><div className="mt-6 flex gap-2 overflow-x-auto border-b border-white/5">{(['overview', 'api', 'usage', 'logs', 'settings'] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-4 py-3 font-display text-xs font-bold capitalize ${tab === item ? 'border-cyan-400 text-cyan-400' : 'border-transparent text-slate-500 hover:text-white'}`}>{item}</button>)}</div>{tab === 'overview' && <Overview deployment={deployment} />} {tab === 'api' && <ApiPanel endpoint={endpoint} apiKey={apiKey} revealed={revealed} setRevealed={setRevealed} regenerate={() => regenerateApiKey(deployment.id)} copy={copy} codeTab={codeTab} setCodeTab={setCodeTab} />} {tab === 'usage' && <Usage deployment={deployment} />} {tab === 'logs' && <Logs />} {tab === 'settings' && <Settings deployment={deployment} onDelete={() => deleteDeployment(deployment.id)} />}</div>;
};

const Status: React.FC = () => <span className="flex items-center gap-1.5 font-display text-[10px] font-black uppercase text-emerald-400"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]" /> Online</span>;
const Overview: React.FC<{ deployment: any }> = ({ deployment }) => <div className="mt-7"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Requests" value="1,284" /><Metric label="Successful" value="98.7%" tone="text-emerald-400" /><Metric label="Average latency" value="420 ms" /><Metric label="Estimated cost" value="₹103.20" tone="text-cyan-400" /><Metric label="GPU usage" value="64%" /></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl glass-panel p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-display text-sm font-black text-white">Request activity</h2><p className="mt-1 font-sans text-[10px] text-slate-500">Mock requests over the last 24 hours</p></div><BarChart3 size={16} className="text-cyan-400" /></div><div className="mt-8 flex h-40 items-end gap-2">{[32, 46, 39, 65, 52, 78, 58, 88, 74, 92, 68, 84, 64, 76, 90, 72].map((height, index) => <div key={index} className="group flex-1"><div className="rounded-t bg-gradient-to-t from-cyan-600/70 to-emerald-400/80 transition group-hover:from-cyan-400 group-hover:to-emerald-300" style={{ height: `${height}%` }} /></div>)}</div><div className="mt-3 flex justify-between font-mono text-[9px] text-slate-600"><span>00:00</span><span>12:00</span><span>Now</span></div></div><div className="rounded-2xl glass-panel p-5"><h2 className="font-display text-sm font-black text-white">Deployment info</h2><div className="mt-5 flex flex-col gap-4"><Info label="Provider" value="ModelVerse Cloud" /><Info label="Region" value={deployment.region} /><Info label="Compute" value={`${deployment.compute.type} · ${deployment.compute.vram} GB`} /><Info label="Scaling" value={deployment.scaling.mode === 'auto' ? 'Auto Scale · 1-3' : 'Fixed · 1'} /><Info label="Environment" value={deployment.environment} /></div></div></div></div>;
const ApiPanel: React.FC<{ endpoint: string; apiKey: string; revealed: boolean; setRevealed: (value: boolean) => void; regenerate: () => void; copy: (value: string, message: string) => void; codeTab: keyof typeof codeExamples; setCodeTab: (value: keyof typeof codeExamples) => void }> = ({ endpoint, apiKey, revealed, setRevealed, regenerate, copy, codeTab, setCodeTab }) => <div className="mt-7 grid gap-5 lg:grid-cols-5"><div className="space-y-5 lg:col-span-3"><div className="rounded-2xl glass-panel p-5"><h2 className="font-display text-sm font-black text-white">API Endpoint</h2><div className="mt-3 flex items-center justify-between gap-3 rounded-xl bg-black/30 px-3 py-3"><code className="truncate font-mono text-xs text-cyan-300">{endpoint}</code><button onClick={() => copy(endpoint, 'Endpoint copied')} className="text-slate-500 hover:text-white"><Copy size={14} /></button></div></div><div className="rounded-2xl glass-panel p-5"><div className="flex items-center justify-between"><div><h2 className="font-display text-sm font-black text-white">API Key</h2><p className="mt-1 font-sans text-[10px] text-slate-500">Prototype key only. No real access is granted.</p></div><KeyRound size={16} className="text-cyan-400" /></div><div className="mt-3 flex items-center justify-between gap-3 rounded-xl bg-black/30 px-3 py-3"><code className="font-mono text-xs text-slate-300">{apiKey}</code><div className="flex gap-2"><button onClick={() => setRevealed(!revealed)} className="font-display text-[10px] font-bold text-cyan-400">{revealed ? 'Hide' : 'Reveal'}</button><button onClick={regenerate} className="font-display text-[10px] font-bold text-cyan-400">Regenerate</button></div></div></div><div className="rounded-2xl glass-panel p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-sm font-black text-white">Quick Start</h2><p className="mt-1 font-sans text-[10px] text-slate-500">Example code for a future integration. It does not work yet.</p></div><Terminal size={16} className="text-cyan-400" /></div><div className="mt-4 flex gap-1">{(Object.keys(codeExamples) as Array<keyof typeof codeExamples>).map((key) => <button key={key} onClick={() => setCodeTab(key)} className={`rounded-lg px-3 py-1.5 font-display text-[10px] font-bold ${codeTab === key ? 'bg-cyan-500/10 text-cyan-400' : 'text-slate-500 hover:text-white'}`}>{key}</button>)}</div><pre className="mt-3 overflow-x-auto rounded-xl border border-white/5 bg-[#08090c] p-4 font-mono text-[10px] leading-relaxed text-slate-300">{codeExamples[codeTab]}</pre><button onClick={() => copy(codeExamples[codeTab], 'Example code copied')} className="mt-3 flex items-center gap-2 font-display text-[10px] font-bold uppercase text-cyan-400"><Clipboard size={13} /> Copy Code</button></div></div><ConnectCards /></div>;
const ConnectCards: React.FC = () => <div className="rounded-2xl border border-cyan-500/15 bg-cyan-500/5 p-5 lg:col-span-2"><h2 className="font-display text-lg font-black text-white">Add AI to your website</h2><p className="mt-1 font-sans text-xs text-slate-400">Illustrative connection options for the future.</p><div className="mt-5 flex flex-col gap-3"><Connect title="JavaScript SDK" description="Install the ModelVerse SDK." code="npm install @modelverse/sdk" /><Connect title="REST API" description="Call your model from any backend." code="POST /v1/your-deployment" /><Connect title="Web Component" description="Add a ready-made AI component." code={'<modelverse-chat model="your-deployment" />'} /></div></div>;
const Connect: React.FC<{ title: string; description: string; code: string }> = ({ title, description, code }) => <div className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="font-display text-xs font-bold text-white">{title}</p><p className="mt-1 font-sans text-[10px] text-slate-500">{description}</p><code className="mt-2 block truncate font-mono text-[10px] text-cyan-300">{code}</code></div>;
const Usage: React.FC<{ deployment: any }> = ({ deployment }) => <div className="mt-7 rounded-2xl glass-panel p-6"><h2 className="font-display text-lg font-black text-white">Usage analytics</h2><p className="mt-1 font-sans text-xs text-slate-500">Mock billing and traffic history for {deployment.name}.</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="This month" value="₹103.20" tone="text-cyan-400" /><Metric label="Peak traffic" value="92 req/min" /><Metric label="Data processed" value="4.8 GB" /></div></div>;
const Logs: React.FC = () => <div className="mt-7 rounded-2xl glass-panel p-6"><div className="flex items-center gap-2"><FileText size={16} className="text-cyan-400" /><h2 className="font-display text-lg font-black text-white">Deployment logs</h2></div><div className="mt-5 rounded-xl bg-black/40 p-4 font-mono text-[10px] leading-loose text-slate-400"><p><span className="text-emerald-400">[healthy]</span> inference service health check passed</p><p><span className="text-cyan-400">[info]</span> mock request router ready</p><p><span className="text-cyan-400">[info]</span> autoscaling policy active</p><p><span className="text-slate-600">[prototype]</span> logs are simulated locally</p></div></div>;
const Settings: React.FC<{ deployment: any; onDelete: () => void }> = ({ deployment, onDelete }) => <div className="mt-7 rounded-2xl glass-panel p-6"><div className="flex items-center gap-2"><Settings2 size={16} className="text-cyan-400" /><h2 className="font-display text-lg font-black text-white">Deployment settings</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info label="Environment" value={deployment.environment} /><Info label="Autoscaling" value={deployment.scaling.mode} /><Info label="Minimum instances" value={String(deployment.scaling.minInstances)} /><Info label="Maximum instances" value={String(deployment.scaling.maxInstances)} /></div><button onClick={onDelete} className="mt-8 flex items-center gap-2 rounded-xl border border-rose-500/20 bg-rose-500/5 px-4 py-2.5 font-display text-xs font-bold text-rose-400"><Trash2 size={14} /> Stop deployment</button></div>;
const Metric: React.FC<{ label: string; value: string; tone?: string }> = ({ label, value, tone = 'text-slate-200' }) => <div className="rounded-xl border border-white/5 bg-white/[0.02] p-4"><span className="font-sans text-[9px] font-bold uppercase tracking-wider text-slate-500">{label}</span><strong className={`mt-2 block font-display text-xl font-black ${tone}`}>{value}</strong></div>;
const Info: React.FC<{ label: string; value: string }> = ({ label, value }) => <div><span className="block font-sans text-[9px] uppercase tracking-wider text-slate-600">{label}</span><span className="mt-1 block font-display text-xs font-bold capitalize text-slate-300">{value}</span></div>;
